server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /health/live {
        add_header Content-Type application/json;
        return 200 '{"status":"live"}';
    }

    location /health/ready {
        add_header Content-Type application/json;
        return 200 '{"status":"ready"}';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
