apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: campushub
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - apps.yaml
images:
  - name: campushub/identity
    newTag: local
  - name: campushub/catalog
    newTag: local
  - name: campushub/enrollment
    newTag: local
  - name: campushub/payment
    newTag: local
  - name: campushub/notification
    newTag: local
  - name: campushub/access
    newTag: local
  - name: campushub/chat
    newTag: local
  - name: campushub/web
    newTag: local
  - name: campushub/gateway
    newTag: local
