<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="OpenIddict.AspNetCore" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\aspire\CampusHub.ServiceDefaults\CampusHub.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\building-blocks\CampusHub.BuildingBlocks\CampusHub.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
